### ISSUE TITLE
[ErrorException]   mkdir(): No such file or directory

### ISSUE THREAD

**Issue by vlahde** [zachleigh/laravel-vue-generators#3]
Hello, on Windows I get this error when try to run php artisan vueg:component Cashier

[ErrorException]
  mkdir(): No such file or directory

Defining path does not help either

**Comment by zachleigh** [comment]
Does the error message tell you a file name and line number? If it includes a stack trace, please post it.

**Comment by vlahde** [comment]
Yeah in the log:
`local.ERROR: exception 'ErrorException' with message 'mkdir(): No such file or directory' in E:\Laravel\sk5.3\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:419`

**Comment by zachleigh** [comment]
@vlahde I think the problem was that I was hardcoding the root path to '/' which I believe is invalid on Windows. I may have fixed it, but I don't have a Windows machine to test it on. I pushed the potential fix up to 'dev-dev' so if you could test it, that would be great. Change your composer.json file entry to `"zachleigh/laravel-vue-generators": "dev-dev"`, run `composer update zachleigh/laravel-vue-generators` and you should be able to pull it in and test it.

**Comment by almaweb** [comment]
Hello,
I just tested in a windows machine and it s work with fix..

**Comment by zachleigh** [comment]
@almaweb Thank you! I merged the dev branch into master and tagged a new release, v0.1.3.

**Comment by vlahde** [comment]
Now it works on windows too. Thanks, great job!
